### PR TITLE
Homepage v2

### LINKED ISSUE #39: Choose Facility dropdown not dynamic
Choose Facility dropdown selections are currently not dynamic, and is only populated when 'load' button is clicked and facillity type is selected

### PR DESCRIPTION
**Pull request by jawsvk**
Fixes #39 

Fixing by adding jquery function to booking.js as well as getFacilities() response body into BookingController.

Please review.

### CODE REVIEW

**Comment by jawsvk** [comment]
Fixes #46 
disabled past dates in timepacker on homepage and booking page

Fixes #37 
put validation check from homepage>booking page
user must input BOTH facility type and date

**Comment by natebakescakes** [comment]
### Fixes #37 
- Validation does not work for me. Submitting when leaving FacilityType and/or Date blank will still navigate me to a blank booking site:

image
image

### Fixes #39 
- Able to load facilities after selecting facility type. However, schedule does not reload. If I'm not logged in, and I click the load button, it brings me to the login page. After logging in, brings me to 400 STATUS. How do I reload the schedule?

image

### Fixes #46 
- I'm not sure how you are currently implementing the validation. I'm able to select past dates on my calendar picker and go all the way to make booking:

image
image
image

If you make any changes, please merge the latest commits from master.

**Comment by jawsvk** [comment]
For Fix #46 

Make sure that the input tag inside home.jsp is 
"input name="date" class="form-control datepicker" id="datepicker" style="text-align:center""

Make sure in home.js  has the following code inside $(document).ready
	$('.datepicker').datepicker({
		todayHighlight: true,
		format: 'dd/mm/yyyy',
		startDate: "0d"
	});

**Review by natebakescakes — APPROVED** [review]
Booking page still needs tweaking.

**Pull request merged**
