### PR TITLE
Homepage v2

### PR DESCRIPTION
**Pull request by jawsvk**
update to fix 
issue 1: 'booking complete' image not loading on booking details page after new booking successful
solution: change c:if tag to detect for request method. since homepage >booking details is using POST, and booking>booking details is via GET

issue 2: booking page timepicker not displaying right timing passed from homepage
solution: in booking.js the timepicker is loaded to display default time of 9:00AM. if this is removed, booking page can load to display the correct start time, end time parameters passed from homepage

minor issues:
formatting of checkbox button on homepage of admin for maintenance booking
formatting of booking details page

### CODE REVIEW

**Comment by natebakescakes** [comment]
Still unable to get to the booking complete page. Same as before.

image

**Comment by jawsvk** [comment]
@natebakescakes  
To get to the booking page, please enter a date. This error occurs because date is not selected, hence the controller is trying to convert a 'null' into a datetimeformatter, which then throws this error.

**Comment by natebakescakes** [comment]
I pushed a fix to the authentication. It made a nullpointer because I wasn't authenticated and it was trying to get an authentication object. As per my suggestion, I pointed the submit button to a page that is hidden behind a login gate to force the user to the login before doing the booking. Please pull the latest changes of this branch.

**Review by natebakescakes — APPROVED** [review]
My bookings and manage booking still not working on this pull request.

**Comment by natebakescakes** [comment]
Fixes #33 
Fixes #35

**Pull request merged**
